services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns
      - DEBUG=1
    healthcheck:
      test: ["CMD", "bash", "-c", "awslocal sqs list-queues >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
