[package]
name = "lab1_sqs_hello_queue"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
shared = { path = "../../shared" }
clap = { workspace = true }
tracing = { workspace = true }

[lib]
path = "src/lib.rs"